// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuVshd3gbtEFS3Iw7iXzRXmMZyYbdqRUE',
    appId: '1:576332255051:web:d4648f278dfc994c75a2ce',
    messagingSenderId: '576332255051',
    projectId: 'campus-battle',
    authDomain: 'campus-battle.firebaseapp.com',
    storageBucket: 'campus-battle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGlKQJQRWZf_1_OPNyAeX4ZLFr7PL9bZI',
    appId: '1:576332255051:android:0aac01653ff93dd475a2ce',
    messagingSenderId: '576332255051',
    projectId: 'campus-battle',
    storageBucket: 'campus-battle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwL0Ya4xF_tWU1fRZCIvFce7nZsdAuxRE',
    appId: '1:576332255051:ios:2eaf65384b9545d575a2ce',
    messagingSenderId: '576332255051',
    projectId: 'campus-battle',
    storageBucket: 'campus-battle.appspot.com',
    iosClientId: '576332255051-a8r28qg0foqnd7qsbjsb9krentfamk9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusbattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwL0Ya4xF_tWU1fRZCIvFce7nZsdAuxRE',
    appId: '1:576332255051:ios:2eaf65384b9545d575a2ce',
    messagingSenderId: '576332255051',
    projectId: 'campus-battle',
    storageBucket: 'campus-battle.appspot.com',
    iosClientId: '576332255051-a8r28qg0foqnd7qsbjsb9krentfamk9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusbattle',
  );
}
